#define ENCODER_PULSES   4096.0
#define STEPPER_PULSES   4000.0
#define LEADSCREW_PITCH  2.0
#define FEEDSCREW_PITCH  (LEADSCREW_PITCH * 0.18)
#define DRIVE_RATIO      4.0

#define REVERSE_DIRECTION TRUE

#define DEFAULT_UNIT    0
#define DEFAULT_VALUE   2

